import type { EntityDef } from './builders';

/** Module packs: ready-made modules built only with the public builders (no special code). Installing one just creates configuration. */
const ANY = ['*'];
const f = (key: string, label: string, type: EntityDef['fields'][number]['type'], required = false, options?: string[]): EntityDef['fields'][number] => ({ key, label, type, required, options, showInList: true, searchable: true });
const flow = (...s: [string, string][]) => s.map(([key, label]) => ({ key, label }));

export interface PackDef extends EntityDef { pack: string; publicForm?: { slug: string; notifyRole: string } }

export const MODULE_PACKS: PackDef[] = [
  { pack: 'church', key: 'pastoral_care', name: 'Pastoral Care', plural: 'Pastoral Care visits', prefix: 'PCV', description: 'Visits, counselling and follow-up for members.',
    fields: [f('member', 'Member', 'text', true), f('visit_date', 'Visit date', 'date', true), f('kind', 'Kind of care', 'select', true, ['Home visit', 'Hospital visit', 'Counselling', 'Prayer request', 'Bereavement']), f('summary', 'Summary', 'longtext', true), f('follow_up', 'Follow-up needed', 'boolean')],
    statuses: flow(['new', 'New'], ['assigned', 'Assigned'], ['done', 'Completed']), transitions: [{ from: 'new', to: 'assigned', roles: [] }, { from: 'assigned', to: 'done', roles: [] }],
    access: { view: ['tenant_admin', 'department_head', 'hr_manager', 'executive'], create: ['tenant_admin', 'department_head', 'hr_manager'], edit: ['tenant_admin', 'department_head', 'hr_manager'], remove: ['tenant_admin'] } },
  { pack: 'school', key: 'student_affairs', name: 'Student Affairs', plural: 'Student Affairs cases', prefix: 'STU', description: 'Welfare, conduct and support cases for students.',
    fields: [f('student', 'Student name', 'text', true), f('class', 'Class', 'text'), f('category', 'Category', 'select', true, ['Welfare', 'Conduct', 'Health', 'Attendance', 'Fees']), f('details', 'Details', 'longtext', true)],
    statuses: flow(['open', 'Open'], ['in_progress', 'In progress'], ['resolved', 'Resolved']), transitions: [{ from: 'open', to: 'in_progress', roles: [] }, { from: 'in_progress', to: 'resolved', roles: ['department_head', 'hr_manager', 'tenant_admin'] }],
    access: { view: ['tenant_admin', 'department_head', 'hr_manager'], create: ['tenant_admin', 'department_head', 'hr_manager'], edit: ['tenant_admin', 'department_head', 'hr_manager'], remove: ['tenant_admin'] } },
  { pack: 'hospital', key: 'patient_services', name: 'Patient Services', plural: 'Patient Services requests', prefix: 'PSV', description: 'Patient requests, feedback and service recovery.',
    fields: [f('patient_ref', 'Patient reference', 'text', true), f('ward', 'Ward / unit', 'text'), f('request', 'Request or concern', 'longtext', true), f('priority', 'Priority', 'select', true, ['Routine', 'Urgent'])],
    statuses: flow(['new', 'New'], ['acknowledged', 'Acknowledged'], ['closed', 'Closed']), transitions: [{ from: 'new', to: 'acknowledged', roles: [] }, { from: 'acknowledged', to: 'closed', roles: [] }],
    access: { view: ['tenant_admin', 'department_head', 'hr_manager'], create: ANY, edit: ['tenant_admin', 'department_head'], remove: ['tenant_admin'] } },
  { pack: 'company', key: 'procurement', name: 'Procurement', plural: 'Purchase requisitions', prefix: 'PRQ', description: 'Requests to buy goods or services, routed for approval.',
    fields: [f('item', 'Item or service', 'text', true), f('quantity', 'Quantity', 'number', true), f('estimate', 'Estimated cost', 'currency', true), f('justification', 'Justification', 'longtext', true), f('needed_by', 'Needed by', 'date')],
    statuses: flow(['requested', 'Requested'], ['approved', 'Approved'], ['ordered', 'Ordered'], ['received', 'Received'], ['rejected', 'Rejected']),
    transitions: [{ from: 'requested', to: 'approved', roles: ['department_head', 'ceo', 'executive'] }, { from: 'requested', to: 'rejected', roles: ['department_head', 'ceo', 'executive'] }, { from: 'approved', to: 'ordered', roles: ['finance_officer', 'finance_manager'] }, { from: 'ordered', to: 'received', roles: [] }],
    access: { view: ANY, create: ANY, edit: ['tenant_admin', 'finance_manager'], remove: ['tenant_admin'] } },
  { pack: 'government', key: 'public_complaints', name: 'Public Complaints', plural: 'Public complaints', prefix: 'CMP', description: 'Complaints from the public, received through a public web form.',
    fields: [f('name', 'Your name', 'text', true), f('phone', 'Phone', 'phone'), f('email', 'Email', 'email'), f('office', 'Office or service concerned', 'text', true), f('complaint', 'Complaint', 'longtext', true)],
    statuses: flow(['received', 'Received'], ['investigating', 'Investigating'], ['resolved', 'Resolved']), transitions: [{ from: 'received', to: 'investigating', roles: [] }, { from: 'investigating', to: 'resolved', roles: ['department_head', 'tenant_admin'] }],
    access: { view: ['tenant_admin', 'department_head', 'executive'], create: ['tenant_admin'], edit: ['tenant_admin', 'department_head'], remove: ['tenant_admin'] }, publicForm: { slug: 'complaints', notifyRole: 'tenant_admin' } },
  { pack: 'radio', key: 'studio_booking', name: 'Studio Booking', plural: 'Studio bookings', prefix: 'STB', description: 'Book recording and production studios.',
    fields: [f('studio', 'Studio', 'select', true, ['Studio 1 (On-air)', 'Studio 2 (Production)', 'Voice booth']), f('date', 'Date', 'date', true), f('start', 'Start time', 'text', true), f('end', 'End time', 'text', true), f('purpose', 'Purpose', 'text', true), f('producer', 'Producer', 'employee')],
    statuses: flow(['requested', 'Requested'], ['confirmed', 'Confirmed'], ['cancelled', 'Cancelled']), transitions: [{ from: 'requested', to: 'confirmed', roles: ['department_head', 'tenant_admin'] }, { from: 'requested', to: 'cancelled', roles: [] }, { from: 'confirmed', to: 'cancelled', roles: ['department_head', 'tenant_admin'] }],
    access: { view: ANY, create: ANY, edit: ['tenant_admin', 'department_head'], remove: ['tenant_admin'] } },
  { pack: 'radio', key: 'programme_log', name: 'Programme Log', plural: 'Programme logs', prefix: 'LOG', description: 'Record what aired, issues, and handover notes.',
    fields: [f('programme', 'Programme', 'text', true), f('air_date', 'Air date', 'date', true), f('presenter', 'Presenter', 'employee'), f('issues', 'Issues or incidents', 'longtext'), f('handover', 'Handover note', 'longtext')],
    statuses: flow(['logged', 'Logged'], ['reviewed', 'Reviewed']), transitions: [{ from: 'logged', to: 'reviewed', roles: ['department_head', 'tenant_admin', 'executive'] }],
    access: { view: ANY, create: ANY, edit: ['tenant_admin', 'department_head'], remove: ['tenant_admin'] } },
  { pack: 'radio', key: 'ad_spots', name: 'Advert Spots', plural: 'Advert spots', prefix: 'ADS', description: 'Schedule and track paid advert spots against campaigns.',
    fields: [f('advertiser', 'Advertiser', 'text', true), f('campaign', 'Campaign', 'text', true), f('spots_per_day', 'Spots per day', 'number', true), f('start', 'Start date', 'date', true), f('end', 'End date', 'date', true), f('rate', 'Rate per spot', 'currency')],
    statuses: flow(['booked', 'Booked'], ['running', 'Running'], ['completed', 'Completed']), transitions: [{ from: 'booked', to: 'running', roles: ['sales', 'department_head', 'tenant_admin'] }, { from: 'running', to: 'completed', roles: ['sales', 'department_head', 'tenant_admin'] }],
    access: { view: ['tenant_admin', 'sales', 'department_head', 'executive', 'ceo', 'finance_manager', 'accountant'], create: ['sales', 'tenant_admin'], edit: ['sales', 'tenant_admin'], remove: ['tenant_admin'] } },
];

export interface OrgTemplate { key: string; label: string; description: string; terms?: Record<string, { singular: string; plural: string }>; departments: string[]; positions: [string, number][]; branchName: string; primary: string; secondary: string; accent: string; packs: string[] }

const std: [string, number][] = [['Head', 1], ['Director', 10], ['Manager', 30], ['Supervisor', 50], ['Officer', 70], ['Assistant', 90]];
export const ORG_TEMPLATES: OrgTemplate[] = [
  { key: 'blank', label: 'Blank enterprise', description: 'Start clean and configure everything yourself.', departments: ['Administration', 'Operations', 'Finance'], positions: std, branchName: 'Head Office', primary: '#12284C', secondary: '#0F766E', accent: '#B45309', packs: [] },
  { key: 'corporate', label: 'Corporate', description: 'Companies with departments, branches, finance and procurement.', departments: ['Administration', 'Operations', 'Sales & Marketing', 'Finance', 'Human Resources', 'IT'], positions: [['CEO', 1], ['Director', 10], ['Manager', 30], ['Supervisor', 50], ['Officer', 70], ['Intern', 95]], branchName: 'Head Office', primary: '#12284C', secondary: '#0F766E', accent: '#B45309', packs: ['company'] },
  { key: 'radio', label: 'Radio station', description: 'Programming, news, production, engineering, advertising, studio booking.', departments: ['Programmes', 'News', 'Production', 'Engineering', 'Advertising & Traffic', 'Marketing', 'Administration & HR', 'Finance', 'Security'], positions: [['Chairman', 1], ['GCEO', 2], ['CEO', 3], ['Regional Manager', 20], ['Branch Manager', 30], ['Head of Department', 45], ['Manager', 50], ['Supervisor', 60], ['Senior Staff', 70], ['Junior Staff', 80], ['Intern', 90]], branchName: 'Headquarters', primary: '#111111', secondary: '#C8102E', accent: '#FFC700', packs: ['radio'] },
  { key: 'church', label: 'Church / ministry', description: 'Ministries, campuses, pastoral care.', terms: { employee: { singular: 'Staff member', plural: 'Staff' }, department: { singular: 'Ministry', plural: 'Ministries' }, branch: { singular: 'Campus', plural: 'Campuses' }, position: { singular: 'Office', plural: 'Offices' } }, departments: ['Pastoral Care', 'Worship', 'Children', 'Youth', 'Administration'], positions: [['General Overseer', 1], ['Pastor', 20], ['Coordinator', 40], ['Volunteer Lead', 60]], branchName: 'Main Campus', primary: '#4C1D95', secondary: '#0E7490', accent: '#B45309', packs: ['church'] },
  { key: 'school', label: 'School', description: 'Teaching and administrative staff, student affairs.', terms: { department: { singular: 'Department', plural: 'Departments' }, employee: { singular: 'Staff member', plural: 'Staff' } }, departments: ['Academics', 'Student Affairs', 'Administration', 'Bursary', 'Facilities'], positions: [['Principal', 1], ['Vice Principal', 5], ['Head of Department', 20], ['Teacher', 50], ['Administrator', 60]], branchName: 'Main Campus', primary: '#1E3A8A', secondary: '#047857', accent: '#B45309', packs: ['school'] },
  { key: 'hospital', label: 'Hospital / clinic', description: 'Clinical and support departments, shifts, patient services.', departments: ['Medical', 'Nursing', 'Pharmacy', 'Laboratory', 'Administration', 'Finance'], positions: [['Medical Director', 1], ['Head of Unit', 20], ['Consultant', 25], ['Nurse', 50], ['Technician', 60], ['Administrator', 70]], branchName: 'Main Hospital', primary: '#0F766E', secondary: '#1D4ED8', accent: '#B45309', packs: ['hospital'] },
  { key: 'ngo', label: 'NGO', description: 'Programmes, projects, field officers and reporting.', departments: ['Programmes', 'Field Operations', 'Monitoring & Evaluation', 'Finance', 'Administration'], positions: [['Executive Director', 1], ['Programme Manager', 20], ['Field Officer', 50], ['Officer', 70]], branchName: 'Head Office', primary: '#065F46', secondary: '#1D4ED8', accent: '#B45309', packs: [] },
  { key: 'government', label: 'Government office', description: 'Departments, approvals, public complaints.', departments: ['Administration', 'Public Service', 'Planning', 'Finance', 'Legal'], positions: [['Permanent Secretary', 1], ['Director', 10], ['Deputy Director', 20], ['Officer', 60]], branchName: 'Secretariat', primary: '#14532D', secondary: '#1E3A8A', accent: '#B45309', packs: ['government'] },
  { key: 'association', label: 'Association / cooperative', description: 'Membership organisations with committees.', terms: { employee: { singular: 'Member', plural: 'Members' }, department: { singular: 'Committee', plural: 'Committees' } }, departments: ['Executive', 'Membership', 'Finance', 'Welfare'], positions: [['President', 1], ['Secretary', 10], ['Treasurer', 10], ['Member', 90]], branchName: 'Head Office', primary: '#7C2D12', secondary: '#1E3A8A', accent: '#B45309', packs: [] },
];
